// ═══════════════════════════════════════════════════════════
//  CS2 Grenade Bot — База раскидок
//
//  Чтобы добавить видео к раскидке:
//  1. Найдите раскидку по id
//  2. Добавьте YouTube ID в поле ytId
//     Пример: ссылка https://youtu.be/XXXXXXXXXXX
//              ytId:  "XXXXXXXXXXX"
// ═══════════════════════════════════════════════════════════

const MAPS = {
  mirage:  { name: "Mirage",   emoji: "🏙️",  c1: "#1B2B4B", c2: "#4A321A", overviewYtId: "gU6rosu8MHE",
             typeVideos: { smoke: "LFomZyE4M7U", molotov: "UZqCuZavlo0", flash: "UZqCuZavlo0", he: "UZqCuZavlo0" } },
  inferno: { name: "Inferno",  emoji: "🌆",  c1: "#3D0F05", c2: "#8B2800", overviewYtId: "gjLDqhibiNQ",
             typeVideos: { smoke: "D9Dntuy80l4", molotov: "Nw3Gd3VT50A", flash: "Nw3Gd3VT50A", he: "Nw3Gd3VT50A" } },
  dust2:   { name: "Dust 2",   emoji: "🏜️",  c1: "#2B2010", c2: "#5C3D15", overviewUrl: "videos/dust2-grenades.mp4",
             typeVideos: { smoke: "AHeXRtk4Jco", molotov: "_qlYvhjk0Fo", flash: "_qlYvhjk0Fo", he: "_qlYvhjk0Fo" } },
  ancient: { name: "Ancient",  emoji: "🏛️",  c1: "#0F2A18", c2: "#1E4A2A", overviewYtId: "aiVZVJzod7o",
             typeVideos: { smoke: "Vq2XL6ZemQk", molotov: "aiVZVJzod7o", flash: "aiVZVJzod7o", he: "aiVZVJzod7o" } },
  nuke:    { name: "Nuke",     emoji: "☢️",  c1: "#0F1B2B", c2: "#1E2B3F", overviewYtId: "gXqYFjHauCM",
             typeVideos: { smoke: "AXFPoVEgXPY", molotov: "gXqYFjHauCM", flash: "gXqYFjHauCM", he: "gXqYFjHauCM" } },
  anubis:  { name: "Anubis",   emoji: "🐾",  c1: "#251A00", c2: "#4A3200", overviewYtId: "1Xe2-ymHTfQ",
             typeVideos: { smoke: "tKQuhZOnNZc", molotov: "1Xe2-ymHTfQ", flash: "1Xe2-ymHTfQ", he: "1Xe2-ymHTfQ" } },
  vertigo: { name: "Vertigo",  emoji: "🏗️",  c1: "#0F1520", c2: "#1E2A3D", overviewYtId: "fj1bWi06UWI",
             typeVideos: { smoke: "fj1bWi06UWI", molotov: "fj1bWi06UWI", flash: "fj1bWi06UWI", he: "fj1bWi06UWI" } },
};

const TYPES = {
  smoke:   { name: "Смоки",    emoji: "💨", color: "#60A5FA" },
  molotov: { name: "Молотовы", emoji: "🔥", color: "#F97316" },
  flash:   { name: "Флешки",   emoji: "⚡", color: "#EAB308" },
  he:      { name: "HE",       emoji: "💥", color: "#EF4444" },
};

// ────────────────────────────────────────────────────────────
// LINEUPS
// ytId: YouTube video ID (пусто → "Видео скоро")
// steps: шаги инструкции (массив строк)
// tip: финальная подсказка
// ────────────────────────────────────────────────────────────
const LINEUPS = [

  // ═══════ MIRAGE ═══════════════════════════════════════════

  { id:"mir_smk_01", map:"mirage", type:"smoke", difficulty:"easy",
    name:"CT Smoke", from:"T-спавн (центр)", to:"CT Connector",
    ytId:"LFomZyE4M7U",
    steps:["Встаньте по центру T-спавна у линии",
           "Прицельтесь в правый верхний угол арки апса",
           "Обычный бросок (левый клик)"],
    tip:"Закрывает CT от апса при пуше на A-сайт" },

  { id:"mir_smk_02", map:"mirage", type:"smoke", difficulty:"medium",
    name:"Jungle Smoke", from:"T-спавн (лево)", to:"Jungle",
    ytId:"LFomZyE4M7U",
    steps:["Встаньте у левого угла T-спавна, прислонитесь к стене",
           "Поднимите прицел чуть выше крыши левого здания",
           "Обычный бросок — граната перелетает крышу"],
    tip:"Перекрывает Jungle при заходе на A-сайт" },

  { id:"mir_smk_03", map:"mirage", type:"smoke", difficulty:"medium",
    name:"Stairs Smoke", from:"T апс (у ящиков)", to:"Лестницы CT",
    ytId:"LFomZyE4M7U",
    steps:["Встаньте у больших ящиков в T апсе",
           "Смотрите на верхний левый угол окна апса",
           "Прыжок + бросок одновременно (jumpthrow)"],
    tip:"Закрывает снайперскую позицию на лестницах CT" },

  { id:"mir_smk_04", map:"mirage", type:"smoke", difficulty:"easy",
    name:"Van Smoke (B)", from:"B апс", to:"Van",
    ytId:"LFomZyE4M7U",
    steps:["Встаньте у правой стены B апса",
           "Прицельтесь в верхний правый угол входа в B",
           "Обычный бросок"],
    tip:"Закрывает Van при заходе на B-сайт" },

  { id:"mir_smk_05", map:"mirage", type:"smoke", difficulty:"easy",
    name:"Short Smoke (B)", from:"B апс (центр)", to:"Short CT",
    ytId:"LFomZyE4M7U",
    steps:["Встаньте по центру B апса",
           "Прицельтесь в верхний край правой стены тоннеля",
           "Обычный бросок"],
    tip:"Изолирует CT шорт при заходе через B" },

  { id:"mir_smk_06", map:"mirage", type:"smoke", difficulty:"hard",
    name:"Ticket Booth Smoke", from:"T апс A (у большого ящика)", to:"Ticket Booth",
    ytId:"LFomZyE4M7U",
    steps:["Встаньте у большого ящика в T апсе A",
           "Прислонитесь к ящику с правой стороны",
           "Прицельтесь в угол кирпичной стены над аркой",
           "Jumpthrow (прыжок + бросок)"],
    tip:"Полностью перекрывает Ticket Booth" },

  { id:"mir_mol_01", map:"mirage", type:"molotov", difficulty:"medium",
    name:"Ticket Booth Mol", from:"T апс (у правого ящика)", to:"Ticket Booth",
    ytId:"UZqCuZavlo0",
    steps:["Встаньте у правого ящика в T апсе",
           "Прицельтесь в угол арки над Ticket Booth",
           "Обычный бросок — молотов падает прямо в угол"],
    tip:"Выкуривает CT из Ticket Booth" },

  { id:"mir_mol_02", map:"mirage", type:"molotov", difficulty:"easy",
    name:"Bench Molotov (B)", from:"B апс", to:"Bench",
    ytId:"UZqCuZavlo0",
    steps:["Встаньте у левой стены B апса",
           "Прицельтесь над левым краем входа в B",
           "Обычный бросок"],
    tip:"Сжигает позицию Bench — любимое место снайпера" },

  { id:"mir_fl_01", map:"mirage", type:"flash", difficulty:"medium",
    name:"Ramp Pop Flash (A)", from:"Ramp (T сторона)", to:"Верхний апс",
    ytId:"UZqCuZavlo0",
    steps:["Зайдите на Ramp, встаньте у правой стены",
           "Смотрите вверх-вправо на край крыши",
           "Бросьте флешку — рикошетит и слепит A-сайт",
           "Сразу отвернитесь после броска!"],
    tip:"Слепит CT на верхнем апсе и A-сайте" },

  { id:"mir_he_01", map:"mirage", type:"he", difficulty:"hard",
    name:"HE на Stairs (A)", from:"T апс A", to:"Лестницы (под ними)",
    ytId:"UZqCuZavlo0",
    steps:["Встаньте у левой стены T апса A",
           "Прицельтесь в нижний край перил лестниц",
           "Jumpthrow — HE взрывается под перилами"],
    tip:"Наносит урон CT стоящему под лестницами" },

  { id:"mir_smk_07", map:"mirage", type:"smoke", difficulty:"medium",
    name:"Market Window Smoke", from:"T апс A (у больших ящиков)", to:"Market Window",
    ytId:"LFomZyE4M7U",
    steps:["Встаньте у больших ящиков в T апсе A",
           "Прицельтесь в верхний правый угол Market Window",
           "Обычный бросок"],
    tip:"Закрывает Market Window — AWP позицию CT" },

  { id:"mir_smk_08", map:"mirage", type:"smoke", difficulty:"easy",
    name:"Playground Smoke (B)", from:"B апс (у левой стены)", to:"Playground",
    ytId:"LFomZyE4M7U",
    steps:["Встаньте у левой стены B апса",
           "Прицельтесь в правый верхний угол тоннеля",
           "Обычный бросок"],
    tip:"Изолирует Playground при толчке через B" },

  { id:"mir_mol_03", map:"mirage", type:"molotov", difficulty:"medium",
    name:"CT Cross Molotov (A)", from:"T апс A (правый ящик)", to:"CT Cross",
    ytId:"UZqCuZavlo0",
    steps:["Встаньте у правого ящика T апса A",
           "Прицельтесь в угол балкона левого здания",
           "Молотов летит на CT Cross"],
    tip:"Выкуривает CT Cross перед плантом на A" },

  { id:"mir_mol_04", map:"mirage", type:"molotov", difficulty:"easy",
    name:"Short Molotov (B)", from:"B апс (правая стена)", to:"B Short угол",
    ytId:"UZqCuZavlo0",
    steps:["Встаньте у правой стены B апса",
           "Прицельтесь чуть выше правого края входа в B тоннель",
           "Обычный бросок"],
    tip:"Сжигает угол Short при заходе через B тоннель" },

  { id:"mir_fl_02", map:"mirage", type:"flash", difficulty:"easy",
    name:"B Site Pop Flash", from:"B тоннель (выход)", to:"B сайт",
    ytId:"UZqCuZavlo0",
    steps:["Встаньте у выхода из B тоннеля, прижмитесь к левой стене",
           "Смотрите вверх на потолок тоннеля у выхода",
           "Бросьте флешку — рикошетит на сайт",
           "Сразу отвернитесь!"],
    tip:"Слепит CT на B сайте при выходе из тоннеля" },

  { id:"mir_he_02", map:"mirage", type:"he", difficulty:"medium",
    name:"HE в Barrels (A)", from:"T апс A (левый угол)", to:"Barrels у A планта",
    ytId:"UZqCuZavlo0",
    steps:["Встаньте у левого угла T апса A",
           "Прицельтесь в центр верхнего края бочек",
           "Обычный бросок — HE взрывается у бочек"],
    tip:"Наносит урон CT за бочками у A планта" },

  // ═══════ INFERNO ══════════════════════════════════════════

  { id:"inf_smk_01", map:"inferno", type:"smoke", difficulty:"easy",
    name:"CT Smoke (Banana)", from:"T-спавн (у машины)", to:"CT Connector",
    ytId:"D9Dntuy80l4",
    steps:["Встаньте у капота машины в T спавне",
           "Прицельтесь в верхний правый угол здания",
           "Обычный бросок"],
    tip:"Закрывает CT при пуше по Banana" },

  { id:"inf_smk_02", map:"inferno", type:"smoke", difficulty:"medium",
    name:"Pit Smoke (A)", from:"T-спавн (центр)", to:"Pit",
    ytId:"D9Dntuy80l4",
    steps:["Встаньте по центру T спавна у линии",
           "Прицельтесь в верхний угол балкона здания",
           "Обычный бросок"],
    tip:"Закрывает снайпера в Pit при заходе A" },

  { id:"inf_smk_03", map:"inferno", type:"smoke", difficulty:"easy",
    name:"Library Smoke (A)", from:"T апс A (правая стена)", to:"Library",
    ytId:"D9Dntuy80l4",
    steps:["Подойдите к правой стене T апса A",
           "Прицельтесь чуть выше правого угла арки",
           "Обычный бросок"],
    tip:"Закрывает Library — важнейшая позиция CT" },

  { id:"inf_smk_04", map:"inferno", type:"smoke", difficulty:"hard",
    name:"Balcony Smoke (A)", from:"A апс T (левый ящик)", to:"Balcony",
    ytId:"D9Dntuy80l4",
    steps:["Встаньте у левого ящика в A апсе",
           "Смотрите вверх на балкон правого здания",
           "Нужен jumpthrow (прыжок + бросок одновременно)"],
    tip:"Закрывает балкон — снайперская позиция CT" },

  { id:"inf_mol_01", map:"inferno", type:"molotov", difficulty:"medium",
    name:"Car Molotov (B)", from:"Начало Banana", to:"Машина на Banana",
    ytId:"Nw3Gd3VT50A",
    steps:["Встаньте в начале Banana у левой стены",
           "Прицельтесь на верхний угол балкона над Banana",
           "Молотов накрывает машину"],
    tip:"Выкуривает CT прячущегося за машиной" },

  { id:"inf_fl_01", map:"inferno", type:"flash", difficulty:"easy",
    name:"Banana Pop Flash", from:"Начало Banana", to:"Весь Banana",
    ytId:"Nw3Gd3VT50A",
    steps:["Встаньте у левой стены в начале Banana",
           "Смотрите вверх на угол стены над входом",
           "Бросьте флешку — рикошетит вглубь Banana",
           "Сразу отвернитесь!"],
    tip:"Слепит CT по всей длине Banana" },

  { id:"inf_smk_05", map:"inferno", type:"smoke", difficulty:"medium",
    name:"Coffins Smoke (A)", from:"T апс A (у правой стены)", to:"Coffins",
    ytId:"D9Dntuy80l4",
    steps:["Встаньте у правой стены T апса A",
           "Прицельтесь в верхний край левого угла Coffins",
           "Обычный бросок"],
    tip:"Закрывает Coffins — укрытие CT при обороне A" },

  { id:"inf_smk_06", map:"inferno", type:"smoke", difficulty:"hard",
    name:"CT Smoke (A Mid)", from:"T спавн (центральная точка)", to:"CT позиция мид A",
    ytId:"D9Dntuy80l4",
    steps:["Встаньте на центральной линии T спавна",
           "Прицельтесь в верхний угол правого здания напротив",
           "Нужен jumpthrow"],
    tip:"Закрывает CT мид при заходе A через апс" },

  { id:"inf_smk_07", map:"inferno", type:"smoke", difficulty:"easy",
    name:"Arch Smoke (A)", from:"T апс A (левая стена)", to:"Arch",
    ytId:"D9Dntuy80l4",
    steps:["Прислонитесь к левой стене T апса A",
           "Прицельтесь в правый верхний угол арки",
           "Обычный бросок"],
    tip:"Закрывает Arch — позицию CT на выходе" },

  { id:"inf_mol_02", map:"inferno", type:"molotov", difficulty:"medium",
    name:"Fountain Molotov (A)", from:"T апс A (у центра)", to:"Fountain",
    ytId:"Nw3Gd3VT50A",
    steps:["Встаньте по центру T апса A",
           "Прицельтесь в верхнюю часть правой колонны",
           "Молотов летит на Fountain"],
    tip:"Выкуривает CT у Fountain перед плантом" },

  { id:"inf_mol_03", map:"inferno", type:"molotov", difficulty:"easy",
    name:"Apartments Mol (B)", from:"Середина Banana", to:"Apartments вход",
    ytId:"Nw3Gd3VT50A",
    steps:["Встаньте по центру Banana у правой стены",
           "Прицельтесь в верхний левый угол входа в Apartments",
           "Обычный бросок"],
    tip:"Выжигает CT из Apartments при продвижении по Banana" },

  { id:"inf_fl_02", map:"inferno", type:"flash", difficulty:"medium",
    name:"A Short Pop Flash", from:"T апс A (угол)", to:"A Short",
    ytId:"Nw3Gd3VT50A",
    steps:["Встаньте у угла стены T апса перед выходом на A",
           "Смотрите вверх под углом на угол стены",
           "Бросьте флешку — рикошетит в A Short",
           "Отвернитесь сразу!"],
    tip:"Слепит CT на A Short перед штурмом A сайта" },

  { id:"inf_he_01", map:"inferno", type:"he", difficulty:"medium",
    name:"Banana HE (стек)", from:"T спавн (за углом Banana)", to:"Начало Banana",
    ytId:"Nw3Gd3VT50A",
    steps:["Встаньте за углом у входа на Banana",
           "Прицельтесь на уровень голов в начало Banana",
           "Обычный бросок — HE наносит урон стеку CT"],
    tip:"Наносит урон CT стоящим у начала Banana" },

  // ═══════ DUST 2 ═══════════════════════════════════════════

  { id:"d2_smk_01", map:"dust2", type:"smoke", difficulty:"easy",
    name:"Xbox Smoke (Mid)", from:"T-спавн (у ворот)", to:"Xbox",
    ytId:"AHeXRtk4Jco",
    steps:["Встаньте у правого косяка ворот T спавна",
           "Прицельтесь в верхний левый угол арки мида",
           "Обычный бросок"],
    tip:"Закрывает Xbox — ключевая позиция для контроля мида" },

  { id:"d2_smk_02", map:"dust2", type:"smoke", difficulty:"medium",
    name:"CT Smoke (Mid→B)", from:"Mid Doors", to:"CT Spawn",
    ytId:"AHeXRtk4Jco",
    steps:["Откройте Mid Doors, встаньте у правой стены",
           "Прицельтесь в верхний правый угол CT окна",
           "Нужен jumpthrow"],
    tip:"Закрывает CT при сплите через мид и B" },

  { id:"d2_smk_03", map:"dust2", type:"smoke", difficulty:"easy",
    name:"Long Pit Smoke", from:"Long (у ящика)", to:"Pit",
    ytId:"AHeXRtk4Jco",
    steps:["Встаньте у ящика у входа на Long",
           "Прицельтесь в верхний угол левой стены",
           "Обычный бросок"],
    tip:"Закрывает Pit снайпера при пуше Long" },

  { id:"d2_smk_04", map:"dust2", type:"smoke", difficulty:"hard",
    name:"Goose Smoke (A)", from:"Long (у ворот A)", to:"Goose",
    ytId:"AHeXRtk4Jco",
    steps:["Встаньте у левой стены Long у ворот A",
           "Прицельтесь в антенну на крыше здания",
           "Нужен jumpthrow"],
    tip:"Закрывает Goose — любимое место AWP на A" },

  { id:"d2_fl_01", map:"dust2", type:"flash", difficulty:"easy",
    name:"Long Pop Flash", from:"Long (у ворот T)", to:"Long A / Pit",
    ytId:"XcORmf82_iY",
    steps:["Встаньте у левой стены, не заходя в Long",
           "Смотрите вверх в угол стены",
           "Флешка летит за угол и слепит позиции",
           "Сразу отвернитесь после броска!"],
    tip:"Слепит снайпера в Pit и на Long" },

  { id:"d2_mol_01", map:"dust2", type:"molotov", difficulty:"easy",
    name:"Short Corner Mol", from:"Short (у ступенек)", to:"Угол Short A",
    ytId:"XcORmf82_iY",
    steps:["Встаньте у правой стены на Short",
           "Прицельтесь над правым углом стены",
           "Молотов накрывает угол"],
    tip:"Выкуривает CT из угла Short перед заходом A" },

  { id:"d2_smk_05", map:"dust2", type:"smoke", difficulty:"easy",
    name:"B Doors Smoke", from:"B тоннели (вход)", to:"B Doors",
    ytId:"AHeXRtk4Jco",
    steps:["Встаньте у левой стены у входа в B тоннели",
           "Прицельтесь в верхний правый угол B Doors",
           "Обычный бросок"],
    tip:"Закрывает B Doors при быстром толчке через B тоннели" },

  { id:"d2_smk_06", map:"dust2", type:"smoke", difficulty:"medium",
    name:"CT Cross Smoke (B)", from:"B тоннели (выход)", to:"CT Cross",
    ytId:"AHeXRtk4Jco",
    steps:["Выйдите из B тоннелей, встаньте у левой стены",
           "Прицельтесь в верхний угол правого здания CT",
           "Нужен jumpthrow"],
    tip:"Закрывает CT Cross при заходе через B тоннели" },

  { id:"d2_smk_07", map:"dust2", type:"smoke", difficulty:"hard",
    name:"CT Spawn Smoke (A Long)", from:"Long (у ворот A)", to:"CT Spawn угол",
    ytId:"AHeXRtk4Jco",
    steps:["Встаньте у правой колонны у ворот A Long",
           "Прицельтесь в верхний левый угол CT Spawn",
           "Нужен jumpthrow — требует точного позиционирования"],
    tip:"Изолирует CT Spawn при заходе через Long на A" },

  { id:"d2_mol_02", map:"dust2", type:"molotov", difficulty:"medium",
    name:"B Site Back Mol", from:"B тоннели (выход)", to:"B Site задний угол",
    ytId:"XcORmf82_iY",
    steps:["Выйдите из B тоннелей на B сайт",
           "Прицельтесь вверх на угол задней стены сайта",
           "Молотов накрывает задний угол"],
    tip:"Выкуривает CT из заднего угла B сайта" },

  { id:"d2_mol_03", map:"dust2", type:"molotov", difficulty:"easy",
    name:"Long Corner Mol", from:"Long (у ворот A)", to:"Long угол у A",
    ytId:"XcORmf82_iY",
    steps:["Встаньте у ворот A Long",
           "Прицельтесь в левый угол у A Long Doors",
           "Обычный бросок"],
    tip:"Выжигает CT из угла Long перед входом на A" },

  { id:"d2_fl_02", map:"dust2", type:"flash", difficulty:"medium",
    name:"B Site Pop Flash", from:"B тоннели (у выхода)", to:"B сайт",
    ytId:"XcORmf82_iY",
    steps:["Встаньте у правой стены выхода из B тоннелей",
           "Смотрите вверх на потолок тоннеля",
           "Бросьте флешку — рикошетит на B сайт",
           "Отвернитесь сразу!"],
    tip:"Слепит CT на B сайте при выходе из тоннелей" },

  { id:"d2_he_01", map:"dust2", type:"he", difficulty:"medium",
    name:"Tunnels Entry HE", from:"T спавн (перед тоннелями)", to:"Начало B тоннелей",
    ytId:"_qlYvhjk0Fo",
    steps:["Встаньте перед входом в B тоннели",
           "Прицельтесь на уровень голов в тоннель",
           "Обычный бросок — HE взрывается у входа"],
    tip:"Наносит урон CT занявшему позицию в начале тоннелей" },

  // ═══════ ANCIENT ══════════════════════════════════════════

  { id:"anc_smk_01", map:"ancient", type:"smoke", difficulty:"medium",
    name:"Donut Smoke (A)", from:"T апс A (правая стена)", to:"Donut / CT угол",
    ytId:"Vq2XL6ZemQk",
    steps:["Встаньте у правой стены T апса A",
           "Смотрите на правый угол арки Donut",
           "Обычный бросок"],
    tip:"Закрывает CT угол при заходе A через Donut" },

  { id:"anc_smk_02", map:"ancient", type:"smoke", difficulty:"hard",
    name:"CT Main Smoke (A)", from:"T апс A (у статуи)", to:"CT Main",
    ytId:"Vq2XL6ZemQk",
    steps:["Встаньте у постамента статуи в T апсе A",
           "Прицельтесь в верхний правый угол над аркой CT",
           "Нужен jumpthrow"],
    tip:"Изолирует CT main при контроле A" },

  { id:"anc_smk_03", map:"ancient", type:"smoke", difficulty:"medium",
    name:"Mid Smoke", from:"T апс мид", to:"Mid CT",
    ytId:"Vq2XL6ZemQk",
    steps:["Встаньте у левой стены T апса мида",
           "Прицельтесь в правый верхний угол тоннеля",
           "Обычный бросок"],
    tip:"Закрывает CT в мид-тоннеле" },

  { id:"anc_mol_01", map:"ancient", type:"molotov", difficulty:"medium",
    name:"B Stairs Molotov", from:"B апс (правая стена)", to:"Лестницы B",
    ytId:"aiVZVJzod7o",
    steps:["Встаньте у правой стены B апса",
           "Прицельтесь на угол перил лестницы",
           "Молотов летит на лестницы"],
    tip:"Выкуривает CT на лестницах B" },

  { id:"anc_smk_04", map:"ancient", type:"smoke", difficulty:"easy",
    name:"Cave Smoke (A)", from:"T апс A (центр)", to:"Cave вход",
    ytId:"Vq2XL6ZemQk",
    steps:["Встаньте по центру T апса A",
           "Прицельтесь в верхний правый угол входа в Cave",
           "Обычный бросок"],
    tip:"Закрывает Cave — укрытие CT при обороне A" },

  { id:"anc_smk_05", map:"ancient", type:"smoke", difficulty:"medium",
    name:"Water Smoke (B)", from:"B апс (левая стена)", to:"Water выход",
    ytId:"Vq2XL6ZemQk",
    steps:["Встаньте у левой стены B апса",
           "Прицельтесь в верхний угол Water выхода",
           "Обычный бросок"],
    tip:"Закрывает Water выход при заходе на B" },

  { id:"anc_smk_06", map:"ancient", type:"smoke", difficulty:"hard",
    name:"Temple Smoke (A)", from:"T спавн (у правой стены)", to:"Temple позиция",
    ytId:"Vq2XL6ZemQk",
    steps:["Встаньте у правой стены T спавна",
           "Прицельтесь в верхний угол Temple здания",
           "Нужен jumpthrow"],
    tip:"Закрывает Temple — снайперскую позицию CT на A" },

  { id:"anc_mol_02", map:"ancient", type:"molotov", difficulty:"medium",
    name:"A Donut Molotov", from:"T апс A (правый угол)", to:"Donut угол",
    ytId:"aiVZVJzod7o",
    steps:["Встаньте у правого угла T апса A",
           "Прицельтесь в нижний угол Donut позиции",
           "Молотов накрывает Donut"],
    tip:"Выкуривает CT из Donut при заходе на A сайт" },

  { id:"anc_mol_03", map:"ancient", type:"molotov", difficulty:"easy",
    name:"B Site Corner Mol", from:"B апс (центр)", to:"B сайт (левый угол)",
    ytId:"aiVZVJzod7o",
    steps:["Встаньте по центру B апса",
           "Прицельтесь в левый угол B сайта",
           "Обычный бросок"],
    tip:"Выжигает CT из угла B сайта перед плантом" },

  { id:"anc_fl_01", map:"ancient", type:"flash", difficulty:"medium",
    name:"A Site Pop Flash", from:"T апс A (у стены)", to:"A сайт",
    ytId:"aiVZVJzod7o",
    steps:["Встаньте у правой стены T апса A",
           "Смотрите вверх на угол стены над выходом",
           "Бросьте флешку — рикошетит на A сайт",
           "Отвернитесь сразу!"],
    tip:"Слепит CT на A сайте при штурме" },

  { id:"anc_fl_02", map:"ancient", type:"flash", difficulty:"easy",
    name:"Mid Pop Flash", from:"Mid (T сторона)", to:"Mid CT позиция",
    ytId:"aiVZVJzod7o",
    steps:["Встаньте у левой стены мид тоннеля",
           "Смотрите вверх на потолок тоннеля",
           "Бросьте флешку — рикошетит на CT",
           "Отвернитесь сразу!"],
    tip:"Слепит CT в мид тоннеле" },

  { id:"anc_he_01", map:"ancient", type:"he", difficulty:"medium",
    name:"B Ramp HE", from:"B апс (перед входом)", to:"B Ramp позиция",
    ytId:"aiVZVJzod7o",
    steps:["Встаньте перед выходом на B Ramp",
           "Прицельтесь в нижнюю часть Ramp позиции",
           "Обычный бросок"],
    tip:"Наносит урон CT, удерживающему Ramp на B" },

  // ═══════ NUKE ═════════════════════════════════════════════

  { id:"nuke_smk_01", map:"nuke", type:"smoke", difficulty:"easy",
    name:"Hut Smoke", from:"Outside (T)", to:"Hut вход",
    ytId:"AXFPoVEgXPY",
    steps:["Встаньте у левой стены снаружи",
           "Прицельтесь в верхний угол Hut",
           "Обычный бросок"],
    tip:"Закрывает Hut при заходе снаружи" },

  { id:"nuke_smk_02", map:"nuke", type:"smoke", difficulty:"hard",
    name:"Rafters Smoke (A Upper)", from:"Hut / Radio", to:"Rafters",
    ytId:"AXFPoVEgXPY",
    steps:["Зайдите в Hut, встаньте у левой стены",
           "Смотрите вверх на люк Rafters",
           "Нужен jumpthrow через люк"],
    tip:"Закрывает Rafters — снайперская позиция на A" },

  { id:"nuke_smk_03", map:"nuke", type:"smoke", difficulty:"medium",
    name:"Garage Smoke", from:"T апс гаража", to:"Garage вход",
    ytId:"AXFPoVEgXPY",
    steps:["Встаньте у правой стены T апса гаража",
           "Прицельтесь в верхний угол ворот",
           "Обычный бросок"],
    tip:"Закрывает выход из Garage при заходе B Lower" },

  { id:"nuke_mol_01", map:"nuke", type:"molotov", difficulty:"medium",
    name:"Mini Molotov (B Lower)", from:"B Lower апс", to:"Mini позиция",
    ytId:"nH_yaNNyzB8",
    steps:["Зайдите в B Lower, встаньте у правой стены",
           "Прицельтесь в угол Mini позиции",
           "Молотов накрывает Mini"],
    tip:"Выкуривает CT с позиции Mini на B Lower" },

  { id:"nuke_smk_04", map:"nuke", type:"smoke", difficulty:"medium",
    name:"Squeaky Smoke", from:"Ramp (у двери Squeaky)", to:"Squeaky проём",
    ytId:"AXFPoVEgXPY",
    steps:["Встаньте у двери Squeaky на Ramp",
           "Прицельтесь в верхний левый угол проёма",
           "Обычный бросок"],
    tip:"Закрывает проём Squeaky при заходе в B Lower" },

  { id:"nuke_smk_05", map:"nuke", type:"smoke", difficulty:"hard",
    name:"Outside CT Smoke", from:"Outside (T позиция)", to:"CT выход Outside",
    ytId:"AXFPoVEgXPY",
    steps:["Встаньте у правой стены снаружи",
           "Прицельтесь в верхний правый угол CT здания",
           "Нужен jumpthrow"],
    tip:"Закрывает CT выход снаружи при заходе A Upper" },

  { id:"nuke_smk_06", map:"nuke", type:"smoke", difficulty:"medium",
    name:"Lobby Smoke (B Upper)", from:"Ramp (начало)", to:"CT Lobby",
    ytId:"AXFPoVEgXPY",
    steps:["Встаньте в начале Ramp у левой стены",
           "Прицельтесь в верхний угол CT Lobby",
           "Обычный бросок"],
    tip:"Закрывает CT Lobby при заходе через B Upper" },

  { id:"nuke_mol_02", map:"nuke", type:"molotov", difficulty:"medium",
    name:"Secret Molotov", from:"Secret коридор", to:"Secret угол",
    ytId:"nH_yaNNyzB8",
    steps:["Зайдите в Secret коридор",
           "Встаньте у левой стены",
           "Прицельтесь в угол Secret позиции CT",
           "Обычный бросок"],
    tip:"Выкуривает CT из Secret при входе через воду" },

  { id:"nuke_mol_03", map:"nuke", type:"molotov", difficulty:"easy",
    name:"Ramp Molotov (CT угол)", from:"Ramp (середина)", to:"CT угол у Ramp выхода",
    ytId:"nH_yaNNyzB8",
    steps:["Встаньте в середине Ramp",
           "Прицельтесь в нижний угол CT выхода с Ramp",
           "Обычный бросок"],
    tip:"Выжигает CT из угла у выхода Ramp" },

  { id:"nuke_fl_01", map:"nuke", type:"flash", difficulty:"medium",
    name:"Outside Pop Flash (A Upper)", from:"Outside (T левая стена)", to:"A Upper сайт",
    ytId:"1I1E9QYCNFg",
    steps:["Встаньте у левой стены снаружи",
           "Смотрите вверх на угол крыши здания",
           "Бросьте флешку — рикошетит на A Upper",
           "Отвернитесь сразу!"],
    tip:"Слепит CT на A Upper при заходе снаружи" },

  { id:"nuke_he_01", map:"nuke", type:"he", difficulty:"hard",
    name:"B Lower Garage HE", from:"Garage (T сторона)", to:"B Lower апс CT",
    ytId:"gXqYFjHauCM",
    steps:["Встаньте у ворот Garage на T стороне",
           "Прицельтесь в верхний угол B Lower апса CT",
           "Нужен jumpthrow"],
    tip:"Наносит урон CT в B Lower апсе через Garage" },

  // ═══════ VERTIGO ══════════════════════════════════════════

  { id:"vert_smk_01", map:"vertigo", type:"smoke", difficulty:"medium",
    name:"CT Smoke (A)", from:"T апс A (у стены)", to:"CT выход",
    ytId:"fj1bWi06UWI",
    steps:["Прислонитесь к правой стене T апса A",
           "Прицельтесь в угол трубы над CT выходом",
           "Обычный бросок"],
    tip:"Изолирует CT при атаке A сайта" },

  { id:"vert_smk_02", map:"vertigo", type:"smoke", difficulty:"hard",
    name:"B CT Smoke", from:"T апс B", to:"CT B выход",
    ytId:"fj1bWi06UWI",
    steps:["Встаньте у левого края T апса B",
           "Прицельтесь в верхний угол вентиляции",
           "Нужен jumpthrow"],
    tip:"Закрывает CT выход B при атаке через B" },

  { id:"vert_mol_01", map:"vertigo", type:"molotov", difficulty:"medium",
    name:"A Site Corner Mol", from:"T апс A (центр)", to:"A плант (левый угол)",
    ytId:"fj1bWi06UWI",
    steps:["Встаньте у центра T апса A",
           "Прицельтесь в верхний угол стены над плантом",
           "Молотов накрывает угол у A планта"],
    tip:"Выкуривает CT из левого угла A" },

  { id:"vert_smk_03", map:"vertigo", type:"smoke", difficulty:"medium",
    name:"Mid Smoke (A→B)", from:"Mid (T сторона)", to:"Mid CT позиция",
    ytId:"fj1bWi06UWI",
    steps:["Встаньте у левой стены мид на T стороне",
           "Прицельтесь в верхний правый угол мид коридора",
           "Обычный бросок"],
    tip:"Закрывает CT в мид при сплите A и B" },

  { id:"vert_smk_04", map:"vertigo", type:"smoke", difficulty:"hard",
    name:"Scaffolding Smoke (A)", from:"T апс A (у левой стены)", to:"Scaffolding",
    ytId:"fj1bWi06UWI",
    steps:["Встаньте у левой стены T апса A",
           "Прицельтесь в верхний угол Scaffolding",
           "Нужен jumpthrow"],
    tip:"Закрывает Scaffolding — AWP позицию CT на A" },

  { id:"vert_smk_05", map:"vertigo", type:"smoke", difficulty:"easy",
    name:"B Ramp Smoke", from:"T апс B (правая стена)", to:"B Ramp выход",
    ytId:"fj1bWi06UWI",
    steps:["Встаньте у правой стены T апса B",
           "Прицельтесь в верхний угол B Ramp выхода",
           "Обычный бросок"],
    tip:"Закрывает B Ramp при заходе на B сайт" },

  { id:"vert_mol_02", map:"vertigo", type:"molotov", difficulty:"medium",
    name:"Mid Molotov (CT угол)", from:"Mid T сторона", to:"CT Mid угол",
    ytId:"fj1bWi06UWI",
    steps:["Встаньте в начале мид коридора T стороны",
           "Прицельтесь в нижний угол CT мид",
           "Обычный бросок"],
    tip:"Выкуривает CT из угла мид коридора" },

  { id:"vert_mol_03", map:"vertigo", type:"molotov", difficulty:"easy",
    name:"B Site Back Mol", from:"T апс B (центр)", to:"B сайт задний угол",
    ytId:"fj1bWi06UWI",
    steps:["Встаньте по центру T апса B",
           "Прицельтесь в задний угол B сайта",
           "Обычный бросок"],
    tip:"Выжигает CT из заднего угла B сайта" },

  { id:"vert_fl_01", map:"vertigo", type:"flash", difficulty:"medium",
    name:"A Site Pop Flash", from:"T апс A (левый угол)", to:"A сайт",
    ytId:"fj1bWi06UWI",
    steps:["Встаньте у левого угла T апса A",
           "Смотрите вверх на потолок апса",
           "Бросьте флешку — рикошетит на A сайт",
           "Отвернитесь сразу!"],
    tip:"Слепит CT при штурме A сайта" },

  { id:"vert_fl_02", map:"vertigo", type:"flash", difficulty:"easy",
    name:"B Pop Flash", from:"T апс B (у правой стены)", to:"B сайт",
    ytId:"fj1bWi06UWI",
    steps:["Встаньте у правой стены T апса B",
           "Смотрите вверх на правый угол потолка апса",
           "Бросьте флешку — рикошетит на B сайт",
           "Отвернитесь сразу!"],
    tip:"Слепит CT при выходе на B сайт" },

  { id:"vert_he_01", map:"vertigo", type:"he", difficulty:"medium",
    name:"A Boost HE", from:"T апс A (у стены)", to:"A Boost позиция CT",
    ytId:"KASlUcNyNX0",
    steps:["Встаньте у левой стены T апса A",
           "Прицельтесь в Boost позицию у правой стены A сайта",
           "Обычный бросок"],
    tip:"Наносит урон CT на Boost позиции у A сайта" },

  // ═══════ ANUBIS ═══════════════════════════════════════════

  { id:"anu_smk_01", map:"anubis", type:"smoke", difficulty:"easy",
    name:"CT Smoke (B)", from:"B апс (правая стена)", to:"CT угол",
    ytId:"tKQuhZOnNZc",
    steps:["Встаньте у правой стены B апса",
           "Прицельтесь в верхний правый угол арки",
           "Обычный бросок"],
    tip:"Перекрывает CT при заходе B" },

  { id:"anu_smk_02", map:"anubis", type:"smoke", difficulty:"medium",
    name:"A Exit Smoke (Water)", from:"Mid (через воду)", to:"A выход",
    ytId:"tKQuhZOnNZc",
    steps:["Войдите в воду на мид",
           "Встаньте у правой стены канала",
           "Прицельтесь в верхний угол A выхода",
           "Обычный бросок"],
    tip:"Закрывает A выход при сплите через воду" },

  { id:"anu_fl_01", map:"anubis", type:"flash", difficulty:"easy",
    name:"B Pop Flash", from:"B тоннель (у стены)", to:"B сайт",
    ytId:"GUz7TAGl4qY",
    steps:["Встаньте у правой стены B тоннеля",
           "Смотрите вверх на потолок тоннеля",
           "Бросьте флешку — рикошетит на сайт",
           "Сразу отвернитесь!"],
    tip:"Слепит CT на B при быстром выходе из тоннеля" },

  { id:"anu_smk_03", map:"anubis", type:"smoke", difficulty:"medium",
    name:"Bridge Smoke (A)", from:"T спавн (у левой стены)", to:"Bridge",
    ytId:"tKQuhZOnNZc",
    steps:["Встаньте у левой стены T спавна",
           "Прицельтесь в верхний правый угол колонны Bridge",
           "Обычный бросок"],
    tip:"Закрывает Bridge при заходе A через мид" },

  { id:"anu_smk_04", map:"anubis", type:"smoke", difficulty:"hard",
    name:"Palace CT Smoke", from:"B апс (у колонны)", to:"CT Palace выход",
    ytId:"tKQuhZOnNZc",
    steps:["Встаньте у ближней колонны B апса",
           "Прицельтесь в верхний угол CT Palace арки",
           "Нужен jumpthrow"],
    tip:"Изолирует CT Palace при заходе на B сайт" },

  { id:"anu_smk_05", map:"anubis", type:"smoke", difficulty:"easy",
    name:"Mid Canal Smoke", from:"T спавн (у правой стены)", to:"Mid Canal CT",
    ytId:"tKQuhZOnNZc",
    steps:["Встаньте у правой стены T спавна",
           "Прицельтесь в верхний левый угол Mid Canal",
           "Обычный бросок"],
    tip:"Закрывает CT в Mid Canal при контроле мида" },

  { id:"anu_mol_01", map:"anubis", type:"molotov", difficulty:"medium",
    name:"B Doorway Molotov", from:"B апс (центр)", to:"B Doorway CT",
    ytId:"GUz7TAGl4qY",
    steps:["Встаньте по центру B апса",
           "Прицельтесь в верхний правый угол B Doorway",
           "Молотов накрывает Doorway"],
    tip:"Выкуривает CT из B Doorway при заходе B" },

  { id:"anu_mol_02", map:"anubis", type:"molotov", difficulty:"easy",
    name:"A Site Corner Mol", from:"T спавн (A апс)", to:"A сайт левый угол",
    ytId:"GUz7TAGl4qY",
    steps:["Встаньте у левой стены A апса",
           "Прицельтесь в левый угол A сайта",
           "Обычный бросок"],
    tip:"Выжигает CT из угла A сайта перед плантом" },

  { id:"anu_fl_02", map:"anubis", type:"flash", difficulty:"medium",
    name:"A Short Pop Flash", from:"A апс (T сторона)", to:"A Short CT",
    ytId:"GUz7TAGl4qY",
    steps:["Встаньте у левой стены A апса",
           "Смотрите вверх на угол стены у A Short",
           "Бросьте флешку — рикошетит на A Short",
           "Отвернитесь сразу!"],
    tip:"Слепит CT на A Short при штурме A сайта" },

  { id:"anu_he_01", map:"anubis", type:"he", difficulty:"medium",
    name:"Mid Water HE", from:"Mid (T вход в воду)", to:"Mid Water CT позиция",
    ytId:"1Xe2-ymHTfQ",
    steps:["Встаньте у входа в воду на мид",
           "Прицельтесь на уровень голов CT позиции",
           "Обычный бросок"],
    tip:"Наносит урон CT в воде на Mid" },
];
